---
- name: Set up HAProxy Load Balancer
  hosts: load_balancer
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          # Global settings
          global
              log /dev/log local0
              log /dev/log local1 notice
              chroot /var/lib/haproxy
              stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
              stats timeout 30s
              user haproxy
              group haproxy
              daemon

          # Default SSL material locations
              ca-base /etc/ssl/certs
              crt-base /etc/ssl/private

          # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
              ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
              ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
              ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

          defaults
              log global
              mode http
              option httplog
              option dontlognull
              timeout connect 5000
              timeout client 50000
              timeout server 50000
              retries 3
              errorfile 400 /etc/haproxy/errors/400.http
              errorfile 403 /etc/haproxy/errors/403.http
              errorfile 408 /etc/haproxy/errors/408.http
              errorfile 500 /etc/haproxy/errors/500.http
              errorfile 502 /etc/haproxy/errors/502.http
              errorfile 503 /etc/haproxy/errors/503.http
              errorfile 504 /etc/haproxy/errors/504.http

          # Frontend configuration
          frontend http_front
              bind *:80
              default_backend http_back

          # Backend configuration
          backend http_back
              mode http
              balance roundrobin
              option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
              server container1 10.51.101.69:80 check
              server container2 10.51.101.167:80 check backup
              server container3 10.51.101.52:80 check backup

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Enable HAProxy on boot
      service:
        name: haproxy
        enabled: true

